version: '3.4'

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  

volumes:
  pgdata:
